version: '3.7'

services:
  db:
    image: postgis/postgis # use lighter image TODO
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dummy_pg_user
      - POSTGRES_PASSWORD=dummy_pg_pwd
      - POSTGRES_DB=batid_db

volumes:
  postgres_data:
